### ISSUE TITLE
Submit motion action recognition and prediction work to a Journal

### ISSUE THREAD

**Issue by kouroshD** [ami-iit/element_human-action-intention-recognition#64]

**Comment by kouroshD** [comment]
Following https://github.com/ami-iit/element_human-action-intention-recognition/issues/71#issuecomment-1025802425:
Action points are:
- [ ] Reread the paper and update it. https://github.com/ami-iit/element_human-action-intention-recognition/issues/72
- [ ] Add the whole pipeline of the data-flow starting from the HW to this application in the experiments section https://github.com/ami-iit/element_human-action-intention-recognition/issues/72
- [ ] Add in the appendix the discussion on the back propagation and convergence of SGD optimization
- [ ] Add new nicer figures in possible to the results of the paper
- [ ] Add the prediction uncertainty inference section and results to the paper.

**Comment by kouroshD** [comment]
> - [ ] Add in the appendix the discussion on the back propagation and convergence of SGD optimization
> - [ ] Add the prediction uncertainty inference section and results to the paper.

 There are no space in the paper for these two points, so they are not added. Moreover, they are directly concerned the novelty of the paper.

**Comment by kouroshD** [comment]
This has been done. We submit it to RAL+IROS 2022. Waiting for the review feedbacks. Closing the epic.
